In [1]:
import numpy as np

def compute_parity(mat):
    # Returns (row_parity, col_parity) for even parity
    return np.sum(mat, axis=1) % 2, np.sum(mat, axis=0) % 2


# Create a 4x4 data matrix
data = np.array([
    [0, 1, 1, 0],
    [1, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1]
])

print("Original Data:\n", data)

# Compute original parity bits
row_par, col_par = compute_parity(data)
print("Row Parity:", row_par)
print("Column Parity:", col_par)


# Introduce an error (flip a bit)
data_err = data.copy()
data_err[2, 1] = 1 - data_err[2, 1]

print("\nData with error at (2,1):\n", data_err)

# Recompute parity
new_row_par, new_col_par = compute_parity(data_err)

print("New Row Parity:", new_row_par)
print("New Column Parity:", new_col_par)


# Detect error location
err_row = np.where(new_row_par != row_par)[0]
err_col = np.where(new_col_par != col_par)[0]

if err_row.size == 1 and err_col.size == 1:
    
    error_location = (err_row[0], err_col[0])
    print("\nError detected at:", error_location)

    # Correct the error
    data_err[error_location] = 1 - data_err[error_location]

    print("Corrected Data:\n", data_err)

else:
    print("No single-bit error detected or multiple errors occurred.")

Original Data:
 [[0 1 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [0 1 0 1]]
Row Parity: [0 0 0 0]
Column Parity: [0 1 0 1]

Data with error at (2,1):
 [[0 1 1 0]
 [1 1 0 0]
 [1 1 1 0]
 [0 1 0 1]]
New Row Parity: [0 0 1 0]
New Column Parity: [0 0 0 1]

Error detected at: (np.int64(2), np.int64(1))
Corrected Data:
 [[0 1 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [0 1 0 1]]
